language: python

python: "3.8"

branches:
  only:
    - master

cache: pip
    
install: make install

script:
  - make lint
  - make test

# after_success:
#   - bash <(curl -s https://codecov.io/bash)
